[package]
name = "xc-bot"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2018"
resolver = "2"

[dependencies]
anyhow = "1"
lazy_static = "1.4"
regex = "1.4"
reqwest = { version = "0.11", features = ["rustls-tls-native-roots"], default-features = false }
rss = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"], default-features = false }
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = "0.2"
