version: 2
jobs:

  test:
    docker:
      - image: rust:1.70
    steps:
      - checkout
      - run:
         name: Unset CircleCI's forced conversion of HTTPS->SSH
         command: git config --global --unset "url.ssh://git@github.com.insteadof"
      - restore_cache:
          keys:
            - v2-cargo-cache-{{ arch }}-{{ .Branch }}
            - v2-cargo-cache-{{ arch }}
      - run:
          name: Show versions
          command: rustc --version && cargo --version
      - run:
          name: Build
          command: cargo build
      - run:
          name: Run tests
          command: cargo test
      - save_cache:
          key: v2-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v2-cargo-cache-{{ arch }}
          paths:
            - target
            - /usr/local/cargo

  clippy:
    docker:
      - image: rust:1.70
    steps:
      - checkout
      - run:
         name: Unset CircleCI's forced conversion of HTTPS->SSH
         command: git config --global --unset "url.ssh://git@github.com.insteadof"
      - restore_cache:
          keys:
            - v2-cargo-clippy-cache
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - save_cache:
          key: v2-cargo-clippy-cache
          paths:
            - /usr/local/cargo

  fmt:
    docker:
      - image: rust:1.70
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cargo-fmt-cache
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
      - save_cache:
          key: v2-cargo-fmt-cache
          paths:
            - /usr/local/cargo

  audit:
    docker:
      - image: dbrgn/cargo-audit:latest
    steps:
      - checkout
      - run:
          name: Run cargo-audit
          command: cargo audit

  docker-build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          # The supported versions can be found here: 
          # https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.14
      - run: docker build . --no-cache

  docker-publish:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          # The supported versions can be found here: 
          # https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.14
      - run: |
          export VERSION=$(grep "^version =" Cargo.toml | sed 's/.*"\([^"]*\)".*/\1/')
          export IMAGE=dbrgn/xc-bot
          docker build . --no-cache -t ${IMAGE}:${CIRCLE_BRANCH} -t ${IMAGE}:${VERSION} \
          && docker login -u $DOCKER_LOGIN -p $DOCKER_ACCESS_TOKEN \
          && docker push ${IMAGE}

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test
      - clippy
      - fmt
      - audit
      - docker-publish:
          context: Docker Hub dbrgn
          requires:
            - test
            - clippy
            - fmt
          filters:
            branches:
              only:
                - main

  # Build main branch every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
      - clippy
      - fmt
      - audit
      - docker-publish:
          context: Docker Hub dbrgn
          requires:
            - test
            - clippy
            - fmt
